# Generated by Django 5.1.3 on 2024-12-18 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gt_sessions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="session",
            old_name="program_id",
            new_name="program",
        ),
    ]
