# Generated by Django 5.1.3 on 2024-12-27 05:36

import exercises.models
import sessions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0002_remove_exercise_pub_date"),
        ("gt_sessions", "0002_rename_program_id_session_program"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="num_repetitions",
        ),
        migrations.RemoveField(
            model_name="session",
            name="num_sets",
        ),
        migrations.RemoveField(
            model_name="session",
            name="pub_date",
        ),
        migrations.AddField(
            model_name="session",
            name="end_timestamp",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="start_timestamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name="SessionExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_repetitions", models.IntegerField()),
                ("num_sets", models.IntegerField()),
                ("weight", models.IntegerField()),
                (
                    "exercise",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(exercises.models.Exercise),
                        to="exercises.exercise",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(sessions.models.Session),
                        to="gt_sessions.session",
                    ),
                ),
            ],
        ),
    ]
