# Generated by Django 5.1.3 on 2024-11-23 18:21

import programs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercise_name", models.CharField(max_length=50)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
                (
                    "program",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(programs.models.Program),
                        to="programs.program",
                    ),
                ),
            ],
        ),
    ]
