# Generated by Django 5.1.3 on 2024-11-23 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="pub_date",
        ),
    ]
