swagger: '2.0'
info:
  title: GainsTracker API
  description: Very cool and useful API
  version: v1
host: 127.0.0.1:8000
schemes:
- http
basePath: /api
consumes:
- application/json
produces:
- application/json
securityDefinitions:
  Basic:
    type: basic
security:
- Basic: []
paths:
  /exercises/:
    get:
      operationId: exercises_list
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/Exercise'
      tags:
      - exercises
    post:
      operationId: exercises_create
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/Exercise'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/Exercise'
      tags:
      - exercises
    parameters: []
  /exercises/{id}/:
    get:
      operationId: exercises_read
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Exercise'
      tags:
      - exercises
    put:
      operationId: exercises_update
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/Exercise'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Exercise'
      tags:
      - exercises
    patch:
      operationId: exercises_partial_update
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/Exercise'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Exercise'
      tags:
      - exercises
    delete:
      operationId: exercises_delete
      description: ''
      parameters: []
      responses:
        '204':
          description: ''
      tags:
      - exercises
    parameters:
    - name: id
      in: path
      description: A unique integer value identifying this exercise.
      required: true
      type: integer
  /programs/:
    get:
      operationId: programs_list
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/Program'
      tags:
      - programs
    post:
      operationId: programs_create
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/Program'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/Program'
      tags:
      - programs
    parameters: []
  /programs/{id}/:
    get:
      operationId: programs_read
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Program'
      tags:
      - programs
    put:
      operationId: programs_update
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/Program'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Program'
      tags:
      - programs
    patch:
      operationId: programs_partial_update
      description: ''
      parameters:
      - name: data
        in: body
        required: true
        schema:
          $ref: '#/definitions/Program'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Program'
      tags:
      - programs
    delete:
      operationId: programs_delete
      description: ''
      parameters: []
      responses:
        '204':
          description: ''
      tags:
      - programs
    parameters:
    - name: id
      in: path
      description: A unique integer value identifying this program.
      required: true
      type: integer
definitions:
  Exercise:
    required:
    - exercise_name
    type: object
    properties:
      exercise_name:
        title: Exercise name
        type: string
        maxLength: 50
        minLength: 1
  Program:
    required:
    - program_name
    - pub_date
    type: object
    properties:
      program_name:
        title: Program name
        type: string
        maxLength: 50
        minLength: 1
      pub_date:
        title: Date published
        type: string
        format: date-time
