# Generated by Django 5.1.3 on 2024-12-19 03:34

import schedules.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0002_remove_exercise_pub_date"),
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleExercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("num_repetitions", models.IntegerField()),
                ("num_sets", models.IntegerField()),
                (
                    "exercise",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET("exercises.Exercise"),
                        to="exercises.exercise",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(schedules.models.Schedule),
                        to="schedules.schedule",
                    ),
                ),
            ],
        ),
    ]
