# Generated by Django 5.1.3 on 2024-12-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0002_remove_exercise_pub_date"),
        ("schedules", "0002_scheduleexercise"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="exercises",
            field=models.ManyToManyField(
                through="schedules.ScheduleExercise", to="exercises.exercise"
            ),
        ),
    ]
