# Generated by Django 5.1.3 on 2024-12-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0003_schedule_exercises"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduleexercise",
            name="num_repetitions",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="scheduleexercise",
            name="num_sets",
            field=models.IntegerField(default=5),
        ),
    ]
