# Generated by Django 5.1.3 on 2024-12-21 21:31

import schedules.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0002_remove_exercise_pub_date"),
        ("schedules", "0004_alter_scheduleexercise_num_repetitions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleExerciseWeights",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.IntegerField(default=10)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET("exercises.Exercise"),
                        to="exercises.exercise",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        null=True,
                        on_delete=models.SET(schedules.models.Schedule),
                        to="schedules.schedule",
                    ),
                ),
            ],
        ),
    ]
