# Generated by Django 5.1.3 on 2024-12-21 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exercises", "0002_remove_exercise_pub_date"),
        ("schedules", "0005_scheduleexerciseweights"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ScheduleExerciseWeights",
            new_name="ExerciseWeights",
        ),
    ]
